name: Latest blog post workflow
on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 06:00
  workflow_dispatch:
permissions:
  contents: write # To update README

jobs:
  update-readme-with-blog:
    name: Update this repos README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/benji377"
