name: Latest blog post workflow
on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 06:00
  workflow_dispatch:
permissions:
  contents: write # To update README

jobs:
  update-readme:
    name: Sync Dev.to Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run sync script
        run: python3 update_readme.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          
          # Only commit and push if the README actually changed
          git diff --quiet && git diff --staged --quiet || (git commit -m "bot: sync latest dev.to posts" && git push)
